### ISSUE TITLE
Error: Not a JPEG file: starts with 0x11 0x00

### ISSUE THREAD

**Issue by jetic83** [openslide/openslide#225]
## Context

**Issue type** (bug report or feature request): Error / Bug?
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): Windows 7
**Platform** (e.g. 64-bit x86, 32-bit ARM): 64-bit
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): SVS

## Details

I have one .SVS slide (only this one) that produces an error when I try to open it with openslide.jar. The java application starts, I select the slide, and then the thumbnail and macro and properties are shown correctly. But the actual slide window is gray/empty. The console gives following error (see below).

    C:\Program Files (x86)\openslide\bin>java -jar openslide.jar
    java.io.IOException: Not a JPEG file: starts with 0x11 0x00
        at org.openslide.OpenSlide.checkError(OpenSlide.java:178)
        at org.openslide.OpenSlide.paintRegionARGB(OpenSlide.java:245)
        at org.openslide.OpenSlide.paintRegion(OpenSlide.java:299)
        at org.openslide.gui.OpenSlideView.paintBackingStore(OpenSlideView.java:783)
        at org.openslide.gui.OpenSlideView.paintBackingStore(OpenSlideView.java:768)
        at org.openslide.gui.OpenSlideView.paintComponent(OpenSlideView.java:716)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at javax.swing.JLayeredPane.paint(Unknown Source)
        at javax.swing.JComponent.paintChildren(Unknown Source)
        at javax.swing.JComponent.paintToOffscreen(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
        at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
        at javax.swing.RepaintManager.paint(Unknown Source)
        at javax.swing.JComponent.paint(Unknown Source)
        at java.awt.GraphicsCallback$PaintCallback.run(Unknown Source)
        at sun.awt.SunGraphicsCallback.runOneComponent(Unknown Source)
        at sun.awt.SunGraphicsCallback.runComponents(Unknown Source)
        at java.awt.Container.paint(Unknown Source)
        at java.awt.Window.paint(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at javax.swing.RepaintManager$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
        at javax.swing.RepaintManager.access$1200(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

Interestingly, directly writing a patch with

    C:\Program Files (x86)\openslide\bin>openslide-write-png.exe "604259.svs" 0 0 0 512 512 "test.png"

writes the correct patch without any error.

It seems like the file format is corrupt (some problems with the JPG compression?), But why is `openslide-write-png.exe` tolerant to that? And can the `openslide.jar` also be set tolerant to that?

Note that other .SVS files are working fine.

**Comment by jetic83** [comment]
This might be related to #211

**Comment by pshrest2** [comment]
I am encountering the same issue on some large slides. Has there been any updates on this? This issue has been open for a while.

**Comment by bgilbert** [comment]
If anyone can contribute a sample slide affected by this problem, please [upload it here](https://openslide.org/submit/).
