### ISSUE TITLE
Unrecognized .scn file

### ISSUE THREAD

**Issue by alisalub** [openslide/openslide#230]
**Issue type** (bug report or feature request): Bug report
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): CentOS7
**Platform** (e.g. 64-bit x86, 32-bit ARM):  64bit x86
**OpenSlide version**: 3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): `scn`

## Details
I'm trying to open a .scn file on a CentOS7 machine using the Python API (version 1.1.1). libtiff5 is already installed, and openslide itself was installed using `yum`.

When calling `openslide.OpenSlide(filename)` I receive the following error:
```
Traceback (most recent call last):
  File "/home/alisa/PycharmProjects/openslide/read_data.py", line 7, in <module>
    data = openslide.OpenSlide(filename)
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/site-packages/openslide/__init__.py", line 154, in __init__
    self._osr = lowlevel.open(filename)
  File "/opt/anaconda/anaconda2/envs/oslide/lib/python3.5/site-packages/openslide/lowlevel.py", line 178, in _check_open
    raise OpenSlideError(err)
openslide.lowlevel.OpenSlideError: Couldn't locate TIFF directory for quickhash
```

Thanks.

**Comment by rmd06** [comment]
you can use bioformats to read scn files. scn are not well opened by openslide.
`    out = bfopen('D:\QMDownload\6\[failed_handOK]Leica_scn\Leica-Fluorescence-1.scn');
    aMat(:,:,1) = out{1}{1};
    aMat(:,:,2) = out{1}{2};
    aMat(:,:,3) = out{1}{3};
    imshow(aMat);`

**Comment by bgilbert** [comment]
If anyone can contribute a sample slide affected by this problem, please [upload it here](https://docs.google.com/forms/d/e/1FAIpQLSf4RsqIEVqB_FlY0mJtmi9fhHNSqc_59e4uHIoAgtkbtplH0w/formResponse). If you can authorize us to redistribute the sample in our test dataset, that'd be especially helpful.
