### ISSUE TITLE
large size problem

### ISSUE THREAD

**Issue by dzfowen** [openslide/openslide#233]
Hi, I met a problem about a big size of tif.

I tried to use openslide to show Tumor_005.tif 1.49G in command line, the data is from camelyon16-grand-challenge.
and errors:

OpenSlide('/Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005.tif')
Traceback (most recent call last):
File "", line 1, in 
File "/anaconda/lib/python3.6/site-packages/openslide/init.py", line 154, in init
self._osr = lowlevel.open(filename)
File "/anaconda/lib/python3.6/site-packages/openslide/lowlevel.py", line 174, in _check_open
"Unsupported or missing image file")
openslide.lowlevel.OpenSlideUnsupportedFormatError: Unsupported or missing image file

But when I run with a test.svs 1.8M it works
OpenSlide('/Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/test.svs')

and OpenSlide('/Users/dzf/camelyon16-grand-challenge/data/TrainingData/Train_Tumor/Tumor_005_Mask.tif')  
A tif with 180M size, also works.

It is very strange, please help!  Thanks a lot:)

**Comment by dzfowen** [comment]
I found some data is broken sorry
