### ISSUE TITLE
0  ModuleNotFoundError: No module named 'pixelengine' in python while converting the phiips isyntax format file into OME-TIFF.

### ISSUE THREAD

**Issue by Yadav420dilip** [openslide/openslide#289]
## Context

ModuleNotFoundError: No module named 'pixelengine' in python while converting the phiips isyntax format file into OME-TIFF.

By following this documentation https://www.glencoesoftware.com/blog/2019/12/09/converting-whole-slide-images-to-OME-TIFF.html#footnotes

I used python 3.6 in ubuntu 18.04.

First I download and install the philips sdk(https://www.philips.co.in/healthcare/sites/pathology/about/sdk) as per given instruction in documentation.

Then I downloaded isyntax2raw (https://github.com/glencoesoftware/isyntax2raw) and install it.

After executing this command in terminal
isyntax2raw write_tiles 20200207_140740.isyntax /home/user/tiff_format_image.tiff

The error comes

Traceback (most recent call last): File "/home/dilip/anaconda3/envs/myenv/bin/isyntax2raw", line 11, in load_entry_point('isyntax2raw==0.0.0', 'console_scripts', 'isyntax2raw')() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 490, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2859, in load_entry_point return ep.load() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2450, in load return self.resolve() File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/pkg_resources/init.py", line 2456, in resolve module = import(self.module_name, fromlist=['name'], level=0) File "/home/dilip/anaconda3/envs/myenv/lib/python3.6/site-packages/isyntax2raw-0.0.0-py3.6.egg/isyntax2raw/init.py", line 15, in ModuleNotFoundError: No module named 'pixelengine'

**Comment by bgilbert** [comment]
isyntax2raw does not use OpenSlide, and that is not an OpenSlide error.  I'd recommend contacting the authors of isyntax2raw.
