### ISSUE TITLE
hang with some file

### ISSUE THREAD

**Issue by olivier38070** [openslide/openslide#304]
## Context

**Issue type** (bug report or feature request):  BUG
**Operating system** (e.g. Fedora 24, Mac OS 10.11, Windows 10): 
macos Sierra 10.13.1
**Platform** (e.g. 64-bit x86, 32-bit ARM): 
64 bits
**OpenSlide Python version** (`openslide.__version__`): 
1.1.1
**OpenSlide version** (`openslide.__library_version__`): 
3.4.1
**Slide format** (e.g. SVS, NDPI, MRXS): 
ndpi
## Details

I have an image named 00095251.ndoi. file size is 1.9 Gb
I believe that I clould share the file over my google drive...

it can be opened fine with the free viewer : ndpView2
it report un error in openslide python, when I try to convert it in tiles.

the python hang and do not quit or report error, until I press CTRL + C
it does around 2600 tiles, then hang.

the error are : 
Process TileWorker:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "deepzoom_tile.py", line 74, in run
    tile = dz.get_tile(level, address)
  File "/usr/local/lib/python2.7/site-packages/openslide/deepzoom.py", line 179, in get_tile
    tile = self._osr.read_region(*args)
  File "/usr/local/lib/python2.7/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 259, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
OpenSlideError: Corrupt JPEG data: bad Huffman code
Process TileWorker:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "deepzoom_tile.py", line 74, in run
    tile = dz.get_tile(level, address)
  File "/usr/local/lib/python2.7/site-packages/openslide/deepzoom.py", line 179, in get_tile
    tile = self._osr.read_region(*args)
  File "/usr/local/lib/python2.7/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 259, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
OpenSlideError: Corrupt JPEG data: bad Huffman code
Process TileWorker:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process TileWorker:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "deepzoom_tile.py", line 74, in run
    tile = dz.get_tile(level, address)
  File "/usr/local/lib/python2.7/site-packages/openslide/deepzoom.py", line 179, in get_tile
    self.run()
  File "deepzoom_tile.py", line 74, in run
    tile = self._osr.read_region(*args)
  File "/usr/local/lib/python2.7/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 259, in read_region
    tile = dz.get_tile(level, address)
  File "/usr/local/lib/python2.7/site-packages/openslide/deepzoom.py", line 179, in get_tile
    _read_region(slide, buf, x, y, level, w, h)
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
OpenSlideError: Corrupt JPEG data: bad Huffman code
    tile = self._osr.read_region(*args)
  File "/usr/local/lib/python2.7/site-packages/openslide/__init__.py", line 223, in read_region
    level, size[0], size[1])
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 259, in read_region
    _read_region(slide, buf, x, y, level, w, h)
  File "/usr/local/lib/python2.7/site-packages/openslide/lowlevel.py", line 196, in _check_error
    raise OpenSlideError(err)
OpenSlideError: Corrupt JPEG data: premature end of data segment

then nothing happen.

if I press CTRL + C : 
CTraceback (most recent call last):
  File "deepzoom_tile.py", line 329, in <module>
    opts.workers, opts.with_viewer).run()
  File "deepzoom_tile.py", line 184, in run
    self._run_image()
  File "deepzoom_tile.py", line 209, in _run_image
    tiler.run()
  File "deepzoom_tile.py", line 105, in run
    self._write_tiles()
  File "deepzoom_tile.py", line 125, in _write_tiles
    tilename))
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/queues.py", line 313, in put
    if not self._sem.acquire(block, timeout):
KeyboardInterrupt
MacBook-Pro:python ormaa$ 

this is bad that the image does not work (it work with third party viewer)
but it is really bad that the python process do not quit...

thanks for any advice.

Olivier

**Comment by bgilbert** [comment]
The upload is no longer available after all this time, so I'm unable to check the file.  However, this is likely a duplicate of #272.

`deepzoom_tile.py` is example code and not necessarily fully robust, so it's not surprising if the work queue hangs on OpenSlide errors.  Fixes are welcome, but you'll probably want to use `vips dzsave` instead for better performance.
