### ISSUE TITLE
DICOM J2K wrong color with YBR_ICT and rejects YBR_RCT photometric interpretation

### ISSUE THREAD

**Issue by dclunie** [openslide/openslide#646]
Tested openslide-4.0.0.3-darwin-x86_64.jar as used in QuPath-0.6.0-rc3-x64.

[ICT DICOM files are here](https://www.dropbox.com/scl/fo/onomtza9dti57i7evkcst/AF9olYXlL0Wo8DrsIQuNgTA?rlkey=qf55xbeqbqwlrbq371sasevbo)

[RCT DICOM files are here](https://www.dropbox.com/scl/fo/hrfs31c3jifptoj77sxmk/AHNQaCrBTZBiqx9Ulgi2Bqs?rlkey=0kyeux4ycvw12flh7hozw8i2p)

(these both load and display as expected with BioFormats selected rather than OpenSlide)

w. ICT shows wrong colors:

![CMU-1_SVS_DICOM_j2klossy_ScreenShot_WrongColors](https://github.com/user-attachments/assets/95fe9b9a-dfe1-4a6f-b7d1-f66caa32397a)

w. RCT says:

05:16:16.324	[JavaFX Application Thread]	ERROR	qupath.lib.images.servers.openslide.OpenslideServerBuilder	Unable to open file:/private/tmp/WSI_MultiFrame_j2klossless/img_0.dcm with OpenSlide: Reading /private/tmp/WSI_MultiFrame_j2klossless/img_0.dcm: Unsupported photometric interpretation YBR_RCT for 1.2.840.10008.1.2.4.90	java.io.IOException: Reading /private/tmp/WSI_MultiFrame_j2klossless/img_0.dcm: Unsupported photometric interpretation YBR_RCT for 1.2.840.10008.1.2.4.90
	at qupath.lib.images.servers.openslide.jna.OpenSlide.checkError(OpenSlide.java:147)
	at qupath.lib.images.servers.openslide.jna.OpenSlide.<init>(OpenSlide.java:103)
	at qupath.lib.images.servers.openslide.jna.OpenSlideLoader.openImage(OpenSlideLoader.java:141)
	at qupath.lib.images.servers.openslide.OpenslideImageServer.<init>(OpenslideImageServer.java:144)
	at qupath.lib.images.servers.openslide.OpenslideServerBuilder.buildServer(OpenslideServerBuilder.java:58)
	at qupath.lib.images.servers.ImageServerBuilder$DefaultImageServerBuilder.buildOriginal(ImageServerBuilder.java:366)
	at qupath.lib.images.servers.ImageServerBuilder$AbstractServerBuilder.build(ImageServerBuilder.java:190)
	at qupath.lib.gui.QuPathGUI.openImage(QuPathGUI.java:1722)

**Comment by jcupitt** [comment]
I see this issue with git master openslide too, fwiw.

I'm working on the openslide DICOM loader at the moment, so I can take a look at this too, if you like.

**Comment by dclunie** [comment]
@jcupitt that would be great, thanks.

If you need any more samples let me know. You can probably find lots on [IDC](https://portal.imaging.datacommons.cancer.gov/explore/filters/?Modality_op=OR&Modality=SM) (we use J2k a lot, for SVS files we have converted to DICOM that were scanned and saved as J2K, as well as those we received uncompressed that we saved as lossless J2K (e.g., the [RMS](https://portal.imaging.datacommons.cancer.gov/explore/filters/?Modality_op=OR&Modality=SM&collection_id=rms_mutation_prediction) collection), where for some slides we have multiple images with lossless and lossy J2K variants (e.g. subject [RMS2277](https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.190216830549021758093218389658845293224/series/1.3.6.1.4.1.5962.99.1.3997054311.671539668.1687624267111.4.0))

**Comment by bgilbert** [comment]
Thanks for the report and samples.  I've uploaded both the [ICT](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/CMU-1-JP2K-ICT.zip) and [RCT](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/CMU-1-JP2K-RCT.zip) samples to openslide-testdata per https://github.com/openslide/openslide/issues/662#issuecomment-4591985814.

It turns out the problem comes down to a misunderstanding of Aperio JPEG 2000 compression that carried forward into the DICOM code.  Aperio format 33005 isn't RGB, it's MCT (specifically ICT in my sample) and OpenJPEG automatically transforms this back to RGB on decompression.  Aperio format 33003 is indeed YCbCr, _without_ MCT, so OpenJPEG gives us back the YCbCr received by the encoder.

Probably as a result of this misunderstanding, our existing DICOM samples (converted from the Aperio samples of the same names) have incorrect photometric interpretations:

| Sample | Encoded `PhotometricInterpretation` | Correct  `PhotometricInterpretation` | Notes |
| -- | -- | -- | -- |
| [CMU-1-JP2K-33005](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/CMU-1-JP2K-33005.zip) | `RGB` | `YBR_ICT` | |
| [JP2K-33003-1](https://openslide.cs.cmu.edu/download/openslide-testdata/DICOM/JP2K-33003-1.zip) | `YBR_ICT` | `YBR_FULL_422` | [PS3.5 section 8.2.4](https://dicom.nema.org/medical/dicom/2026a/output/chtml/part05/sect_8.2.4.html) note 3 suggests `YBR_FULL_422` might be permissible, even though it isn't listed in the table.  In any case, no other table value applies here. |

https://github.com/openslide/openslide/pull/743 changes OpenSlide to correctly decode `YBR_ICT` and `YBR_RCT`, thereby breaking the incorrect JP2K-33003-1 sample.  The PR does not add support for `YBR_FULL_422` because I assume that isn't actually a thing.

@dclunie, I noticed the dual-personality TIFF metadata in both of the new samples claims to have TIFF compression 33003, which by my current understanding should be 33005 instead.  It might be good to change the converter logic in PixelMed Java accordingly.
